"use client";

import { useState, useEffect, useCallback } from "react";
import { getStatusColor, formatCurrency } from "@/lib/utils";

interface ClassDraft { classNo:number; title:string; description:string; scheduledDate:string; startTime:string; endTime:string; }
interface Course { id:string; name:string; description:string; duration:string; fee:string; status:string; classCount?:number; }
interface CourseClass { id:string; classNo:number; title:string; description:string|null; scheduledDate:string|null; startTime:string|null; endTime:string|null; status:string; recordingId:string|null; recordingTitle:string|null; videoUrl:string|null; recordingDuration:string|null; }
function newClass(classNo:number):ClassDraft{return{classNo,title:"",description:"",scheduledDate:"",startTime:"",endTime:""};}

export default function CoursesPage(){
 const [courses,setCourses]=useState<Course[]>([]);const[loading,setLoading]=useState(true);const[showModal,setShowModal]=useState(false);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");
 const[classes,setClasses]=useState<ClassDraft[]>(Array.from({length:10},(_,i)=>newClass(i+1)));const[form,setForm]=useState({name:"",description:"",duration:"",fee:""});
 const[editing,setEditing]=useState<Course|null>(null);const[editClasses,setEditClasses]=useState<CourseClass[]>([]);const[editLoading,setEditLoading]=useState(false);const[editSaving,setEditSaving]=useState(false);const[addingEditClass,setAddingEditClass]=useState(false);const[newEditClass,setNewEditClass]=useState({title:"",description:"",scheduledDate:"",startTime:"",endTime:""});
 const[videoClass,setVideoClass]=useState<CourseClass|null>(null);const[videoTitle,setVideoTitle]=useState("");const[videoUrl,setVideoUrl]=useState("");const[videoDuration,setVideoDuration]=useState("");const[videoSaving,setVideoSaving]=useState(false);

 const fetchCourses=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/courses",{cache:"no-store"});const d=await r.json();setCourses(d.courses||[]);}finally{setLoading(false);}},[]);
 useEffect(()=>{void fetchCourses();},[fetchCourses]);

 function openAdd(){setForm({name:"",description:"",duration:"",fee:""});setClasses(Array.from({length:10},(_,i)=>newClass(i+1)));setError("");setShowModal(true);}
 function updateClass(i:number,p:Partial<ClassDraft>){setClasses(prev=>prev.map((x,n)=>n===i?{...x,...p}:x));}
 function addClass(){setClasses(prev=>[...prev,newClass(prev.length+1)]);}
 function removeClass(i:number){setClasses(prev=>prev.filter((_,n)=>n!==i).map((x,n)=>({...x,classNo:n+1})));}

 async function handleSubmit(e:React.FormEvent){e.preventDefault();setSubmitting(true);setError("");try{const r=await fetch("/api/courses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,classes:classes.filter(c=>c.title.trim()).map(c=>({...c,title:c.title.trim(),description:c.description.trim()||null,scheduledDate:c.scheduledDate||null,startTime:c.startTime||null,endTime:c.endTime||null}))})});const d=await r.json();if(!r.ok){setError(d.error||"Failed to create course");return;}setShowModal(false);await fetchCourses();}catch{setError("Failed to create course");}finally{setSubmitting(false);}}
 async function toggleStatus(c:Course){await fetch(`/api/courses/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:c.status==="ACTIVE"?"INACTIVE":"ACTIVE"})});await fetchCourses();}

 async function openEdit(c:Course){setEditing(c);setEditLoading(true);try{const r=await fetch(`/api/courses/${c.id}/classes`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");setEditClasses(d.classes||[]);}catch(e){alert(e instanceof Error?e.message:"Failed to load course classes");setEditing(null);}finally{setEditLoading(false);}}
 async function addEditClass(){if(!editing||!newEditClass.title.trim())return;setAddingEditClass(true);try{const r=await fetch(`/api/courses/${editing.id}/classes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newEditClass)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");setEditClasses(prev=>[...prev,d.class]);setNewEditClass({title:"",description:"",scheduledDate:"",startTime:"",endTime:""});}catch(e){alert(e instanceof Error?e.message:"Failed to add class");}finally{setAddingEditClass(false);}}
 async function saveCourse(){if(!editing)return;setEditSaving(true);try{const r=await fetch(`/api/courses/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editing.name,description:editing.description,duration:editing.duration,fee:editing.fee})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");for(const c of editClasses){await fetch(`/api/courses/${editing.id}/classes`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({classId:c.id,title:c.title,description:c.description,scheduledDate:c.scheduledDate,startTime:c.startTime,endTime:c.endTime,status:c.status})});}setEditing(null);await fetchCourses();}catch(e){alert(e instanceof Error?e.message:"Failed to save course");}finally{setEditSaving(false);}}
 function openVideo(c:CourseClass){setVideoClass(c);setVideoTitle(c.recordingTitle||`Class ${c.classNo} Recording`);setVideoUrl(c.videoUrl||"");setVideoDuration(c.recordingDuration||"");}
 async function saveVideo(e:React.FormEvent){e.preventDefault();if(!editing||!videoClass)return;setVideoSaving(true);try{const r=await fetch(`/api/courses/${editing.id}/recordings`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({classId:videoClass.id,title:videoTitle.trim(),videoUrl:videoUrl.trim(),duration:videoDuration.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");setEditClasses(prev=>prev.map(c=>c.id===videoClass.id?{...c,recordingId:d.recording.id,recordingTitle:d.recording.title,videoUrl:d.recording.videoUrl,recordingDuration:d.recording.duration}:c));setVideoClass(null);}catch(e){alert(e instanceof Error?e.message:"Failed to save video");}finally{setVideoSaving(false);}}
 async function removeVideo(){if(!editing||!videoClass)return;if(!confirm("Remove this class video?"))return;setVideoSaving(true);try{const r=await fetch(`/api/courses/${editing.id}/recordings`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({classId:videoClass.id})});if(!r.ok)throw new Error("Failed");setEditClasses(prev=>prev.map(c=>c.id===videoClass.id?{...c,recordingId:null,recordingTitle:null,videoUrl:null,recordingDuration:null}:c));setVideoClass(null);}catch(e){alert(e instanceof Error?e.message:"Failed");}finally{setVideoSaving(false);}}

 const filledClasses=classes.filter(c=>c.title.trim()).length;
 return <div className="space-y-5">
  <div className="page-header"><div><h1 className="page-title">Courses</h1><p className="text-sm text-slate-500">{courses.length} courses</p></div><button onClick={openAdd} className="btn btn-primary">＋ Add Course</button></div>
  {loading?<div className="flex justify-center py-12"><div className="w-7 h-7 border-4 border-blue-600 border-t-transparent rounded-full animate-spin"/></div>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
   {courses.length===0?<div className="col-span-full text-center py-12"><div className="text-4xl mb-3">📚</div><p className="text-slate-500">No courses yet</p></div>:courses.map(c=><div key={c.id} className="card hover:shadow-md transition-shadow">
    <div className="flex items-start justify-between mb-3"><div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center text-xl">📚</div><span className={`badge ${getStatusColor(c.status)}`}>{c.status}</span></div>
    <h3 className="font-bold text-slate-800 mb-1">{c.name}</h3>{c.description&&<p className="text-sm text-slate-500 mb-3 line-clamp-2">{c.description}</p>}
    <div className="flex items-center justify-between text-sm"><span className="text-slate-500">Duration: <span className="font-medium text-slate-700">{c.duration||"—"}</span></span><span className="font-bold text-blue-600">{c.fee?formatCurrency(c.fee):"Free"}</span></div>
    <div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs font-semibold text-teal-700">{c.classCount||0} Classes</span><div className="flex gap-2"><button onClick={()=>openEdit(c)} className="btn btn-outline btn-sm">Edit</button><button onClick={()=>openEdit(c)} className="btn btn-primary btn-sm">🎥 Videos</button><button onClick={()=>toggleStatus(c)} className={`btn btn-sm btn-outline ${c.status==="ACTIVE"?"text-red-500":"text-green-600"}`}>{c.status==="ACTIVE"?"Deactivate":"Activate"}</button></div></div>
   </div>)}
  </div>}

  {showModal&&<div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&!submitting&&setShowModal(false)}><div className="modal-box course-modal-box"><div className="modal-header"><div><h2 className="modal-title">Add Course</h2><p className="text-xs text-slate-400">Course create করার সময় class / syllabus যোগ করুন।</p></div><button onClick={()=>!submitting&&setShowModal(false)} className="btn btn-ghost btn-sm">✕</button></div>
   <form onSubmit={handleSubmit}><div className="modal-body">{error&&<div className="p-3 bg-red-50 text-red-600 rounded-xl text-sm">{error}</div>}<div><label className="form-label">Course Name *</label><input className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><label className="form-label">Description</label><textarea className="form-input" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="form-label">Duration</label><input className="form-input" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></div><div><label className="form-label">Fee (৳)</label><input type="number" className="form-input" value={form.fee} onChange={e=>setForm({...form,fee:e.target.value})}/></div></div>
    <div className="mt-2 rounded-2xl border border-teal-100 bg-teal-50/40 p-4"><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Course Syllabus / Classes</h3><p className="text-xs text-slate-500">{filledClasses} class titles added</p></div><button type="button" onClick={addClass} className="btn btn-outline btn-sm text-teal-700">+ Add Class</button></div><div className="mt-4 space-y-3">{classes.map((c,i)=><div key={i} className="rounded-xl border border-slate-200 bg-white p-3"><div className="grid grid-cols-1 gap-3 lg:grid-cols-[70px_1fr_170px_115px_115px_auto]"><div><label className="form-label">Class</label><div className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-black text-teal-700">{c.classNo}</div></div><div><label className="form-label">Title</label><input className="form-input" value={c.title} onChange={e=>updateClass(i,{title:e.target.value})}/></div><div><label className="form-label">Date</label><input type="date" className="form-input" value={c.scheduledDate} onChange={e=>updateClass(i,{scheduledDate:e.target.value})}/></div><div><label className="form-label">Start</label><input type="time" className="form-input" value={c.startTime} onChange={e=>updateClass(i,{startTime:e.target.value})}/></div><div><label className="form-label">End</label><input type="time" className="form-input" value={c.endTime} onChange={e=>updateClass(i,{endTime:e.target.value})}/></div><div className="flex items-end"><button type="button" onClick={()=>removeClass(i)} className="btn btn-ghost btn-sm text-red-600">Remove</button></div></div><div className="mt-2"><label className="form-label">Description</label><input className="form-input" value={c.description} onChange={e=>updateClass(i,{description:e.target.value})}/></div></div>)}</div></div>
   </div><div className="modal-footer"><button type="button" onClick={()=>!submitting&&setShowModal(false)} className="btn btn-outline">Cancel</button><button type="submit" disabled={submitting} className="btn btn-primary">{submitting?`Creating...`:`Create Course + ${filledClasses} Classes`}</button></div></form>
  </div></div>}

  {editing&&<div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&!editSaving&&!videoClass&&setEditing(null)}><div className="modal-box max-w-5xl"><div className="modal-header"><div><h2 className="modal-title">Edit Course</h2><p className="text-xs text-slate-400">Edit course details and manage videos class-by-class.</p></div><button onClick={()=>!editSaving&&!videoClass&&setEditing(null)} className="btn btn-ghost btn-sm">✕</button></div>
   {editLoading?<div className="modal-body text-center py-12">Loading course classes...</div>:<><div className="modal-body space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="form-label">Course Name</label><input className="form-input" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></div><div><label className="form-label">Duration</label><input className="form-input" value={editing.duration||""} onChange={e=>setEditing({...editing,duration:e.target.value})}/></div><div><label className="form-label">Fee</label><input className="form-input" value={editing.fee||""} onChange={e=>setEditing({...editing,fee:e.target.value})}/></div><div><label className="form-label">Description</label><input className="form-input" value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></div></div>
    <div className="rounded-2xl border border-slate-200 overflow-hidden"><div className="bg-slate-50 px-4 py-3 flex items-center justify-between"><div className="font-bold">Course Syllabus / Classes</div><button type="button" onClick={()=>setNewEditClass({title:"",description:"",scheduledDate:"",startTime:"",endTime:""})} className="btn btn-outline btn-sm text-teal-700">＋ Add Class</button></div>
    <div className="p-4 border-b border-slate-100 bg-teal-50/30"><div className="grid grid-cols-1 lg:grid-cols-[70px_1fr_150px_110px_110px_auto] gap-2 items-end"><div className="text-xs font-bold text-slate-500">Next</div><input className="form-input" placeholder="Class title *" value={newEditClass.title} onChange={e=>setNewEditClass({...newEditClass,title:e.target.value})}/><input type="date" className="form-input" value={newEditClass.scheduledDate} onChange={e=>setNewEditClass({...newEditClass,scheduledDate:e.target.value})}/><input type="time" className="form-input" value={newEditClass.startTime} onChange={e=>setNewEditClass({...newEditClass,startTime:e.target.value})}/><input type="time" className="form-input" value={newEditClass.endTime} onChange={e=>setNewEditClass({...newEditClass,endTime:e.target.value})}/><button type="button" onClick={addEditClass} disabled={addingEditClass||!newEditClass.title.trim()} className="btn btn-primary btn-sm">{addingEditClass?"Adding...":"Add"}</button></div><input className="form-input mt-2" placeholder="Class description" value={newEditClass.description} onChange={e=>setNewEditClass({...newEditClass,description:e.target.value})}/></div><div className="divide-y divide-slate-100">{editClasses.length===0?<div className="p-5 text-sm text-slate-500">No classes in this course.</div>:editClasses.map((c,i)=><div key={c.id} className="p-4"><div className="flex flex-col lg:flex-row lg:items-center gap-3"><div className="w-14 font-black text-teal-700">Class {c.classNo}</div><div className="flex-1"><input className="form-input font-semibold" value={c.title} onChange={e=>setEditClasses(prev=>prev.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><input className="form-input mt-2 text-xs" value={c.description||""} placeholder="Description" onChange={e=>setEditClasses(prev=>prev.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/></div><button type="button" onClick={()=>openVideo(c)} className={`btn btn-sm ${c.recordingId?"btn-primary":"btn-outline"}`}>{c.recordingId?"🎥 Edit Video":"＋ Add Video"}</button></div>{c.recordingId&&<div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm"><b>{c.recordingTitle}</b>{c.recordingDuration&&<span className="ml-2 text-xs text-slate-500">({c.recordingDuration})</span>}<a href={c.videoUrl||"#"} target="_blank" rel="noreferrer" className="ml-3 text-blue-700 font-semibold">Open Video ↗</a></div>}</div>)}</div></div>
   </div><div className="modal-footer"><button type="button" onClick={()=>!editSaving&&setEditing(null)} className="btn btn-outline">Cancel</button><button type="button" onClick={saveCourse} disabled={editSaving} className="btn btn-primary">{editSaving?"Saving...":"Save Changes"}</button></div></>}
  </div></div>}

  {videoClass&&<div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&!videoSaving&&setVideoClass(null)}><div className="modal-box max-w-xl"><div className="modal-header"><div><h2 className="modal-title">{videoClass.recordingId?"Edit Class Video":"Add Class Video"}</h2><p className="text-xs text-slate-400">Class {videoClass.classNo}: {videoClass.title}</p></div><button onClick={()=>!videoSaving&&setVideoClass(null)} className="btn btn-ghost btn-sm">✕</button></div><form onSubmit={saveVideo}><div className="modal-body space-y-3"><div><label className="form-label">Video Title *</label><input className="form-input" value={videoTitle} onChange={e=>setVideoTitle(e.target.value)} required/></div><div><label className="form-label">Video Link / URL *</label><input type="url" className="form-input" value={videoUrl} onChange={e=>setVideoUrl(e.target.value)} placeholder="https://..." required/><p className="mt-1 text-xs font-medium text-blue-600">Paste your YouTube / Vimeo / direct MP4 video link here.</p></div><div><label className="form-label">Duration</label><input className="form-input" value={videoDuration} onChange={e=>setVideoDuration(e.target.value)} placeholder="45 minutes"/></div></div><div className="modal-footer">{videoClass.recordingId&&<button type="button" onClick={removeVideo} disabled={videoSaving} className="btn btn-ghost text-red-600 mr-auto">Remove Video</button>}<button type="button" onClick={()=>!videoSaving&&setVideoClass(null)} className="btn btn-outline">Cancel</button><button type="submit" disabled={videoSaving} className="btn btn-primary">{videoSaving?"Saving...":"Save Video"}</button></div></form></div></div>}
 </div>;
}
