"use client";

import { FormEvent, useEffect, useState } from "react";

type Semester = { id: string; semesterNo: number; name: string };
type Programme = { id: string; programmeNo: number | null; name: string; code: string | null; duration: string | null; description: string | null; status: string; studentCount: number; semesters: Semester[] };

type FormState = { programmeNo: string; name: string; code: string; duration: string; description: string; semesterCount: string };

const emptyForm: FormState = { programmeNo: "211", name: "", code: "", duration: "", description: "", semesterCount: "4" };

export default function ProgrammesPage() {
  const [programmes,setProgrammes]=useState<Programme[]>([]); const [nextNo,setNextNo]=useState(211); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [deleting,setDeleting]=useState<string|null>(null); const [show,setShow]=useState(false); const [search,setSearch]=useState(""); const [error,setError]=useState(""); const [form,setForm]=useState<FormState>(emptyForm);

  async function load(){try{setLoading(true);setError("");const r=await fetch("/api/programmes",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Failed to load programmes");setProgrammes(d.programmes||[]);const n=Number(d.nextProgrammeNo)||211;setNextNo(n);setForm(f=>({...f,programmeNo:f.name?f.programmeNo:String(n)}));}catch(e){console.error(e);setError(e instanceof Error?e.message:"Failed to load programmes");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);

  function openAdd(){setForm({...emptyForm,programmeNo:String(nextNo)});setError("");setShow(true);}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/programmes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,programmeNo:Number(form.programmeNo),semesterCount:Number(form.semesterCount)})});const d=await r.json();if(!r.ok){setError(d?.error||"Failed to create programme");return;}setShow(false);setForm({...emptyForm,programmeNo:String(nextNo)});await load();}catch(e){console.error(e);setError("Failed to create programme");}finally{setSaving(false);}}
  async function removeProgramme(id:string,name:string){if(!confirm(`Delete programme "${name}"? It can only be deleted when no batches or exams are linked.`))return;setDeleting(id);setError("");try{const r=await fetch(`/api/programmes/${id}`,{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d?.error||"Failed to delete programme");return;}await load();}catch(e){console.error(e);setError("Failed to delete programme");}finally{setDeleting(null);}}

  const filtered=programmes.filter(p=>{const q=search.trim().toLowerCase();if(!q)return true;return p.name.toLowerCase().includes(q)||(p.code||"").toLowerCase().includes(q)||String(p.programmeNo||"").includes(q);});

  return <div className="min-h-screen bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-teal-700 text-white">EL</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-700">ACADEMIC</span></div><h1 className="text-3xl font-bold text-slate-900">Programmes</h1><p className="mt-1 text-sm text-slate-500">Programme numbering starts from 211.</p></div><button onClick={openAdd} className="btn btn-primary">+ Add Programme</button></div>
    {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search programme number, name or code..." className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-teal-500"/></div>
    {loading?<div className="flex justify-center py-12"><div className="h-7 w-7 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"/></div>:filtered.length===0?<div className="card py-12 text-center"><p className="font-semibold text-slate-700">No programmes found</p><button onClick={openAdd} className="btn btn-primary btn-sm mt-4">Add Programme</button></div>:<div className="grid grid-cols-1 gap-5 lg:grid-cols-2">{filtered.map(p=><div key={p.id} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-black text-blue-700">#{p.programmeNo||"—"}</span><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-bold text-emerald-700">{p.status}</span></div><h2 className="mt-2 text-lg font-bold text-slate-900">{p.name}</h2>{p.code&&<p className="mt-1 text-xs font-bold uppercase tracking-wider text-teal-700">Code: {p.code}</p>}</div><div className="flex h-11 w-11 flex-col items-center justify-center rounded-xl bg-teal-50 text-teal-700"><span className="text-base font-black">{p.studentCount ?? 0}</span><span className="text-[8px] font-bold uppercase tracking-wide">Students</span></div></div>{p.description&&<p className="mt-3 text-sm text-slate-600">{p.description}</p>}<div className="mt-4 flex flex-wrap gap-2">{p.duration&&<span className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs text-slate-600">{p.duration}</span>}<span className="rounded-lg bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{p.semesters.length} Semesters</span></div></div><div className="p-5"><h3 className="mb-3 text-sm font-bold text-slate-800">Semester Structure</h3><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{p.semesters.map(s=><div key={s.id} className="rounded-xl border bg-slate-50 px-3 py-3"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Semester</p><p className="mt-1 font-bold text-slate-800">{s.semesterNo}</p><p className="truncate text-xs text-slate-500">{s.name}</p></div>)}</div><div className="mt-5 flex justify-end border-t pt-3"><button onClick={()=>removeProgramme(p.id,p.name)} disabled={deleting===p.id} className="btn btn-ghost btn-sm text-red-600">{deleting===p.id?"Deleting...":"Delete"}</button></div></div></div>)}</div>}

    {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-bold text-slate-900">Add New Programme</h2><p className="text-xs text-slate-500">Programme number starts from 211.</p></div><button onClick={()=>!saving&&setShow(false)} className="btn btn-ghost btn-sm">✕</button></div><form onSubmit={submit} className="p-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="form-label">Programme No *</label><input type="number" min="211" className="form-input font-bold" value={form.programmeNo} onChange={e=>setForm({...form,programmeNo:e.target.value})} required/></div><div><label className="form-label">Programme Name *</label><input className="form-input" placeholder="Graphic Design With AI" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><label className="form-label">Programme Code</label><input className="form-input uppercase" placeholder="GDWAI" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/><p className="mt-1 text-xs text-slate-400">Leave empty for automatic code suggestion.</p></div><div><label className="form-label">Duration</label><input className="form-input" placeholder="e.g. 1 Year" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></div><div><label className="form-label">Semesters *</label><select className="form-select" value={form.semesterCount} onChange={e=>setForm({...form,semesterCount:e.target.value})}>{Array.from({length:27},(_,i)=>i+4).map(n=><option key={n} value={n}>{n} Semesters</option>)}</select></div><div className="sm:col-span-2"><label className="form-label">Description</label><textarea rows={4} className="form-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div><div className="mt-6 flex justify-end gap-3 border-t pt-5"><button type="button" onClick={()=>!saving&&setShow(false)} className="btn btn-outline">Cancel</button><button type="submit" disabled={saving} className="btn btn-primary">{saving?"Creating...":"Create Programme"}</button></div></form></div></div>}
  </div></div>;
}

